language: php

php:
- 7.2

services:
  - docker

before_install:
  - docker pull prestashop/prestashop
  - docker network create prestashop-net
  - docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
  - docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop